hchanhi/Fin_Team_PillGood_Project

- src/main/java/com/pg/model/Achievements.java
- src/main/java/com/pg/model/AchievementsLog.java
- src/main/java/com/pg/model/Rule.java
- src/main/java/com/pg/model/Supplements.java
- src/main/java/com/pg/model/TakingLog.java
create table
- Achievements, AchievementsLog, Rule, Supplements, TakingLog
> [add] add model

- frontend/package-lock.json
- frontend/package.json
- frontend/src/CheckPill.js
- frontend/src/Main.js
- frontend/src/jwtCheck.js
> [add]/ jwt체크 파일

- frontend/src/Header.js
> [modify]/ 헤더 css 수정

- frontend/src/CheckPill.js
- frontend/src/reward/Reward.js
> [add]/ 점심, 저녁 체크리스트 추가

- frontend/src/App.css
- frontend/src/App.js
- frontend/src/Footer.js
- frontend/src/Header.js
- frontend/src/Main.js
- frontend/src/PreMain.js
- frontend/src/login/Login2.js
[modify] / 로그인 전에는 홈 화면 다르게 바꿈
> [modify] / 로그인 전에는 홈 화면 다르게 바꿈

- frontend/src/CheckPill.js
> [modify]/체크리스트 수정

- src/main/java/com/pg/controller/SupplementsController.java
- src/main/java/com/pg/model/Supplements.java
- src/main/java/com/pg/repository/AchievementsRepository.java
- src/main/java/com/pg/service/SupplementsService.java
> [modify] modfiy Add Supplements

- frontend/src/CheckPill.js
- frontend/src/Footer.js
> [add]체크리스트 axios

- src/main/java/com/pg/controller/TakingLogController.java
- src/main/java/com/pg/model/Supplements.java
- src/main/java/com/pg/repository/SupplementsRepository.java
- src/main/java/com/pg/repository/TakingLogRepository.java
- src/main/java/com/pg/service/SupplementsService.java
- src/main/java/com/pg/service/TakingLogService.java
check supplements
uncheck supplements 구현
> [add] add TakingLog

- frontend/src/CheckPill.js
- frontend/src/Main.js
> [modify] 체크리스트 수정

- src/main/java/com/pg/controller/TakingLogController.java
- src/main/java/com/pg/repository/SupplementsRepository.java
- src/main/java/com/pg/service/TakingLogService.java
> [modify] modify TakingLog

- frontend/src/CheckPill.js
> [modify] 체크리스트 비동기통신 수정

- frontend/src/CheckPill.js
> [add] 체크리스트 axios 저녁에 추가

- frontend/src/App.css
- frontend/src/CheckPill.js
- frontend/src/Footer.js
- frontend/src/Header.js
- frontend/src/Main.css
- frontend/src/Main.js
- frontend/src/alarm/MyPill.css
> [modify] 메인 색 수정

- frontend/src/Main.js
- frontend/src/login/Login2.js
- frontend/src/login/Signup.css
- frontend/src/login/Signup.js
> [modify] css 수정

- frontend/src/CheckPill.js
> [modify]/영양제 체크 리스트 수정

- frontend/src/CheckPill.js
- frontend/src/user/User.js
> [modify]/ 회원정보 css 수정

- frontend/src/CheckPill.js
> [modify] /새로고침 시 체크 유지

- frontend/src/CheckPill.js
- frontend/src/Footer.js
- frontend/src/Header.js
- frontend/src/Main.js
- frontend/src/reward/Reward.js
> [delete]필요없는 코드 삭제

- frontend/src/login/Login2.js
- frontend/src/reward/Reward.js
- frontend/src/user/User.js
> [modify]css 수정

- src/main/java/com/pg/controller/RecordController.java
- src/main/java/com/pg/repository/RecordRepository.java
- src/main/java/com/pg/service/RecordService.java
> [add] maxRanking

- frontend/src/Main.js
> [add]Main에 랭킹출력

- frontend/src/alarm/MyPill.js
- frontend/src/login/Signup.css
> [modify] 얼럿창 수정

- frontend/src/alarm/AddPill.css
- frontend/src/alarm/AddPill.js
- frontend/src/alarm/MyPill.css
- frontend/src/alarm/MyPill.js
> [modify] 영양제 css 수정

- src/main/java/com/pg/controller/AcheivementsController.java
- src/main/java/com/pg/model/Achievements.java
- src/main/java/com/pg/repository/AchievementsLogRepository.java
- src/main/java/com/pg/service/AchievementsLogService.java
- src/main/resources/data.sql
> [add] add badge

- frontend/src/Main.js
> [add]/뱃지 axios 추가

- frontend/src/PreMain.css
- frontend/src/PreMain.js
> [modify] / 프리메인페이지 수정

- frontend/src/Main.js
> [modify]/넓이 수정

- frontend/src/Main.css
- frontend/src/Main.js
> [Style] 메인 페이지 수정

- frontend/src/reward/Reward.js
리워드 페이지 하단에 흰 부분이 생겨 height 수정함
> [Style] 리워드 페이지 height 수정

- frontend/src/user/User.css
- frontend/src/user/User.js
회원정보 페이지가 아래로 내려가 보이지 않아 height 수정,
input 박스 길이가 달라 길이 맞춤
> [Style] 회원정보 페이지 수정
